// Certificate timeline data - 2 certificates
// Generated by parse_certificates.py

window.certificateData = [
  {
    "from": "Legal Due Process",
    "from_email": "authority@legaldueprocess.com",
    "subject": "FAO FRANZ WILD| \"IF YOU'RE NOT DEAD\" WESTMINSTER RESPONSE TO HOMELESS SERVICE USER",
    "message_id": "b911b68e-1ed3-4773-db71-4a1ce397d1bf@legaldueprocess.com",
    "delivered_on": "6 Jan, 2026 at 2:55 AM",
    "delivered_to": [
      {
        "name": "",
        "email": "bureaulocal@tbij.com"
      },
      {
        "name": "Leah Farrer",
        "email": "leahfarrer41@icloud.com"
      }
    ],
    "timeline": [
      {
        "type": "opened",
        "date": "11 Jan, 2026",
        "time": "7:23 PM",
        "actor": "garethdavies@tbij.com",
        "datetime": "2026-01-11T19:23:00"
      },
      {
        "type": "opened",
        "date": "6 Jan, 2026",
        "time": "9:25 AM",
        "actor": "garethdavies@tbij.com",
        "datetime": "2026-01-06T09:25:00"
      },
      {
        "type": "link_click",
        "date": "6 Jan, 2026",
        "time": "8:41 AM",
        "actor": "Leah Farrer",
        "datetime": "2026-01-06T08:41:00"
      },
      {
        "type": "opened",
        "date": "6 Jan, 2026",
        "time": "8:38 AM",
        "actor": "Leah Farrer",
        "datetime": "2026-01-06T08:38:00"
      },
      {
        "type": "opened",
        "date": "6 Jan, 2026",
        "time": "6:15 AM",
        "actor": "franzwild@tbij.com",
        "datetime": "2026-01-06T06:15:00"
      },
      {
        "type": "opened",
        "date": "6 Jan, 2026",
        "time": "6:13 AM",
        "actor": "franzwild@tbij.com",
        "datetime": "2026-01-06T06:13:00"
      },
      {
        "type": "opened",
        "date": "6 Jan, 2026",
        "time": "3:34 AM",
        "actor": "garethdavies@tbij.com",
        "datetime": "2026-01-06T03:34:00"
      },
      {
        "type": "opened",
        "date": "6 Jan, 2026",
        "time": "3:33 AM",
        "actor": "garethdavies@tbij.com",
        "datetime": "2026-01-06T03:33:00"
      },
      {
        "type": "link_click",
        "date": "6 Jan, 2026",
        "time": "2:55 AM",
        "actor": "one of the recipients",
        "datetime": "2026-01-06T02:55:00"
      },
      {
        "type": "link_click",
        "date": "6 Jan, 2026",
        "time": "2:55 AM",
        "actor": "one of the recipients",
        "datetime": "2026-01-06T02:55:00"
      },
      {
        "type": "opened",
        "date": "6 Jan, 2026",
        "time": "2:55 AM",
        "actor": "one of the recipients",
        "datetime": "2026-01-06T02:55:00"
      }
    ],
    "filename": "2026-01-06-IF-YOU'RE-NOT-DEAD-WESTMINSTER-RESPONSE--8-3-0.pdf"
  },
  {
    "from": "Legal Due Process",
    "from_email": "authority@legaldueprocess.com",
    "subject": "FAO FRANZ WILD| \"IF YOU'RE NOT DEAD\" WESTMINSTER RESPONSE TO HOMELESS SERVICE USER",
    "message_id": "2130acb8-2086-f159-1d6d-28daf591ab49@legaldueprocess.com",
    "delivered_on": "18 Dec, 2025 at 10:24 AM",
    "delivered_to": [
      {
        "name": "",
        "email": "bureaulocal@tbij.com"
      }
    ],
    "timeline": [
      {
        "type": "opened",
        "date": "5 Jan, 2026",
        "time": "9:53 AM",
        "actor": "garethdavies@tbij.com",
        "datetime": "2026-01-05T09:53:00"
      },
      {
        "type": "opened",
        "date": "19 Dec, 2025",
        "time": "10:09 AM",
        "actor": "franzwild@tbij.com",
        "datetime": "2025-12-19T10:09:00"
      },
      {
        "type": "opened",
        "date": "18 Dec, 2025",
        "time": "10:37 PM",
        "actor": "garethdavies@tbij.com",
        "datetime": "2025-12-18T22:37:00"
      },
      {
        "type": "opened",
        "date": "18 Dec, 2025",
        "time": "11:36 AM",
        "actor": "garethdavies@tbij.com",
        "datetime": "2025-12-18T11:36:00"
      },
      {
        "type": "opened",
        "date": "18 Dec, 2025",
        "time": "10:46 AM",
        "actor": "franzwild@tbij.com",
        "datetime": "2025-12-18T10:46:00"
      }
    ],
    "filename": "2025-12-18-IF-YOU'RE-NOT-DEAD-WESTMINSTER-RESPONSE--5-0-0.pdf"
  }
];
